### ISSUE TITLE
Design: Release note / customer education screen

### ISSUE THREAD

**Issue by geffenz** [zcash/secant-android-wallet#293]
A user needs to be aware of the state of the wallet, what is working and not, and what we would like them to test each release. Additionally, in the final product a user may need to know about updates or network status.

The original release note would be something like:

"We are testing the deployment process, not the app. Feel free to look around but be aware everything is under construction."

Geffen to make screens then hand off to developer.

**Comment by ccjernigan** [comment]
On the release notes, one consideration for the design is to think about the data structure behind each repeatable each release note “block”.  If I had to guess, it is probably going to be a scrolling list of repeating units containing {Version, Date, release notes text body}

The reason to think of it this way, instead of one large free-form text area, is that it will make localization easier and cheaper.  For both Android and iOS, localizations are stored in a localization file with key-value pairs.  We can ship each independent key-value localization pair in that file off for localization.  If we have 1 large blob that keeps having new stuff added at the top, then we have to re-translate the entire blob.  But if we segment it, then we can just relocalize the parts that are new.

This is better:
release_notes_version_june_15 = "1.0"
release_notes_date_june_15 = "June 15"
release_notes_body_june_15 = "First release"
release_notes_version_june_30 = "1.0.1"
release_notes_date_june_30 = "June 30"
release_notes_body_june_30 = "Oops we fixed some bugs"

This is worse:
release_notes = "June 15\n1.0\nFirst release\nJune 30\n1.0.1\nWe fixed some bugs"

Those are just examples. We'll probably end up with something slightly different but it gets the idea across how localization might fit into the design for this.
