### ISSUE TITLE
Robo test on FTL (test_robo_release) job is failing

### ISSUE THREAD

**Issue by HonzaR** [zcash/secant-android-wallet#659]
### Describe the issue
After switching to the Zcash SDK dependency to the latest `1.10.0-beta01-SNAPSHOT` our test_robo_release job experiences failure: `NoSuchMethodError: no non-static method "Lcash/z/ecc/android/sdk/model/UnifiedSpendingKey` on both 27 and 33 Android SDK level emulators on FTL.

Failed [matrix example](https://console.firebase.google.com/u/4/project/android-firebase-b0cf1/testlab/histories/bh.61ab335878181908/matrices/6355247478272271128?hl=en).

It could be the same trouble, which we've started to experience a few weeks ago on SDK robo tests https://github.com/zcash/zcash-android-wallet-sdk/issues/723.

On the other hand the test_robo_debug job seems to be working as expected.

### Can you reliably reproduce the issue?
It seems that every test_robo_release job on FTL will be impacted.

**Comment by str4d** [comment]
The cause is almost certainly this:

https://github.com/zcash/zcash-android-wallet-sdk/blob/103d2748c64be79c396673736e9317422d5bd860/sdk-lib/src/main/rust/lib.rs#L159-L166

I need a way to construct a Kotlin `UnifiedSpendingKey` object via JNI. Originally this was via a public constructor, but @ccjernigan said it was possible to make that constructor private (as it now is: https://github.com/zcash/zcash-android-wallet-sdk/blob/103d2748c64be79c396673736e9317422d5bd860/sdk-lib/src/main/java/cash/z/ecc/android/sdk/model/UnifiedSpendingKey.kt#L14-L26) and it should still be accessible via JNI. If that is not the case, then some other construction mechanism needs to be provided.

**Comment by ccjernigan** [comment]
That private constructor won’t work because it has strong argument types.  The separate `internal` constructor is the correct one for the JNI since it has primitive arguments.  That said, I’m not yet certain whether the constructor is actually the root cause.

We’re checking whether R8 minification/optimization is actually the cause, as we’ve only seen this so far in minified release builds.

**Comment by str4d** [comment]
I've made a PR that alters the `DerivationTool.deriveSpendingKey` JNI method to not construct `UnifiedSpendingKey`, and it now hits a different error: https://github.com/zcash/zcash-android-wallet-sdk/pull/798#issuecomment-1329899730

Did some searching for possibly-related issues: https://github.com/zcash/zcash-android-wallet-sdk/pull/798#issuecomment-1329899730

**Comment by HonzaR** [comment]
This is fixed by https://github.com/zcash/secant-android-wallet/pull/652. We can move discussion to the related SDK issue https://github.com/zcash/zcash-android-wallet-sdk/issues/723.
